name: onCreateTag Actions
run-name: Build the Docker image ${{ github.ref_name }} 🚀
on:
  workflow_run:
    workflows:
      - "onPushToMaster Actions"
    types:
      - "completed"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Get Package version
        run: echo VERSION=$(cat package.json | jq -r '.version') >> $GITHUB_ENV
      - name: Get Package name
        run: echo APP=$(cat package.json | jq -r '.name') >> $GITHUB_ENV
      # - name: Login to Google Artifact Registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: "${{ vars.GAR_LOCATION }}-docker.pkg.dev"
      #     username: _json_key
      #     password: ${{ secrets.GAR_JSON_KEY }}
      # - name: Build the Docker image
      #   run: docker build . --file Dockerfile --tag ${{ github.repository }}:${{ env.VERSION }}
      # - name: Push to Google Artifact Registry
      #   uses: docker/build-push-action@v4
      #   with:
      #     push: true
      #     tags: "${{ vars.GAR_LOCATION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GAR_REPOSITORY }}/${{ env.APP }}:${{ env.VERSION }}"
      - name: Clone the Infra repo
        uses: actions/checkout@v3
        with:
          repository: francois1059/poc-api-infra
          path: infra-repo
      - name: Update the image tag in values
        run: yq '.image.tag = "{{ .env.VERSION }}"' -i infra-repo/poc-api/values.yaml
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
      # - name: This is the end
      #   run: echo "Uncle Ben's"
