name: onCreateTag Actions
run-name: ${{ github.actor }} is building the repo ${{ github.repository }} 🚀
on:
  create:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  GAR_LOCATION: europe-west-9

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Login to Google Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: $GAR_LOCATION-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}
      # - name: Build the Docker image
      #   run: docker build . --file Dockerfile --tag ${{ github.repository }}:${{ github.ref_name }}
      # - name: Push to Artifact Registry
      #   run: echo "Uncle Ben's"