name: onCreateTag Actions
run-name: Build the Docker image ${{ github.ref_name }} 🚀
on:
  workflow_run:
    workflows:
      - "onPushToMaster Actions"
    types:
      - "completed"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Login to Google Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: "${{ vars.GAR_LOCATION }}-docker.pkg.dev"
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}
      # - name: Build the Docker image
      #   run: docker build . --file Dockerfile --tag ${{ github.repository }}:${{ github.ref_name }}
      # - name: Push to Artifact Registry
      #   run: echo "Uncle Ben's"