name: onPushToMaster Actions
run-name: ${{ github.actor }} is building the repo ${{ github.repository }} 🚀
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - run: npm ci
      - name: Linting the code
        run: npm run lint
      - name: Running tests
        run: npm run test